# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170924_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pipelines',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '\u6784\u5efa\u4e2d'), (1, '\u521d\u59cb\u5316'), (2, '\u8fd0\u884c'), (3, '\u505c\u6b62')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_agents',
            field=models.TextField(default='Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0'),
        ),
    ]
