# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
