# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_project_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='callback_func',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56de\u8c03'),
        ),
    ]
